### ISSUE TITLE
"@groupADD" "@groupREMOVE" "permADD" “permREMOVE" didn't work with LuckPerms

### ISSUE THREAD

**Issue by xiangxiangxiong9** [yuttyann/ScriptBlockPlus#15]
I test "@groupADD" "@groupREMOVE" "@permADD" ”@permREMOVE“,in an interact script , but it is nothing happened.
Is it didn't support LuckPerms?
#
[中国語から翻訳]私は「@groupADD」「@groupREMOVE」「@permADD」「@permREMOVE」のインタラクティブシナリオをテストしましたが、反応はありませんでした。
LuckPermsはサポートされていませんか？

**Comment by yuttyann** [comment]
When I installed and checked LukPerms, it was recognized normally.(vault v1.7.1-b91, paper1.15.2)
![debug](https://i.gyazo.com/2cf0a14b0d58269176a5415e4b309887.png)

It may not be compatible with the vault version, so I will investigate.

**Comment by yuttyann** [comment]
I confirmed that the operation was firm.
Below is the reason that seems to be the cause.

If the player has OP or permission, it is a specification that permission cannot be added because the permission possession judgment is valid.
I'm not sure if it will be resolved, but I'm considering updating to v1.9.1.

**Comment by xiangxiangxiong9** [comment]
Oh，it is worked，but it's not LockPerms'notice…
So that I think it isn't work……
