### ISSUE TITLE
1.21 update???

### ISSUE THREAD

**Issue by Lounode** [yuttyann/ScriptBlockPlus#57]
Okay, it's almost September, but the SBP for 1.20 and 1.21 hasn't been updated yet :(

**Comment by yuttyann** [comment]
We are currently behind in supporting 1.20.5 and later versions due to some code differences between spigot and paper.
Another reason for the delay is that we are working on a plug-in that will replace SBP.

Therefore, we would appreciate it if you could wait a little longer for SBP support.
We are planning to release a version of SBP that supports 1.20 or later by the end of September.
